# -*- coding: utf-8 -*-
try:
    import ldap
except ImportError, e:
    pass

bar = False
otherattribute = {
    'key-1': 1,
    'key-2': 2,
}

from fancymod import FancyClass

@somedecorator(name=None)
def somefunction():
    """Docstring of function.
    """
    return \
        foo, \
        bar

class SomeClass(VeryVeryLongClassNameFromSomewhere,
                VeryVeryLongClassNameFromSomewhereElse):
    """Docstring of ``SomeClass``.
    """

    someattribute = u'somevalue'

    ##code-section section-1
    import os
    import sys
    ##/code-section section-1

##code-section section-2
print u'I am the protected section code'
##/code-section section-2

class OtherClass(object):

    def otherfunction(self):
        """I am the Changed Docstring
        """
        raise NotImplementedError("stub generated by AGX.")

    def addedfunc(self):
        """Added function doc
        """
        if True:
            return False