# -*- coding: utf-8 -*-
"""I am a docstring.

Some Documentation.
"""

##code-section section-1
from foo import bar
##/code-section section-1

if foo is None:
    foo = 0

foo, bar = {
    'x': 1,
    'y': 2,
}

import Bar, \
       Baz as XBaz

class SomeClass(Foo, Bar):
    """Docstring of ``SomeClass``.
    """

    someattribute = u'somevalue'
    otherattribute = {
        'key-1': 1,
        'key-2': 2,
    }

    @somedecorator(a)
    def somefunction(self, foo, bar, *args, **kwargs):
        """Docstring of function.
        """
        return \
            foo, \
            bar

class OtherClass(object):

    def otherfunction(self):
        raise NotImplementedError("stub generated by AGX.")