# -*- coding: utf-8 -*-
"""I am the Changed Docstring
"""

##code-section section-1
import os
import sys
##/code-section section-1

try:
    import ldap
except ImportError, e:
    pass

bar = False

from fancymod import FancyClass

class SomeClass(VeryVeryLongClassNameFromSomewhere,
                VeryVeryLongClassNameFromSomewhereElse):
    """Docstring of ``SomeClass``.
    """

    someattribute = u'somevalue'
    otherattribute = {
        'key-1': 1,
        'key-2': 2,
    }

    @somedecorator(name=None)
    def somefunction(self):
        """Docstring of function.
        """
        return \
            foo, \
            bar

    ##code-section section-2
    print u'I am the protected section code'
    ##/code-section section-2

class OtherClass(object):

    def otherfunction(self):
        raise NotImplementedError("stub generated by AGX.")

    def addedfunc(self):
        """Added function doc
        """
        if True:
            return False